# Generated by Django 5.1.7 on 2025-12-06 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('early_repayment_discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted')], default='active', max_length=10)),
                ('current_balalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
