# Generated by Django 6.0 on 2025-12-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='current_balalance',
            new_name='current_balance',
        ),
    ]
