# Generated by Django 6.0 on 2025-12-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_current_balalance_loan_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='max_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
